[workspace]
resolver = "2"
members = [
    "components/*/src/..",
    "crates/*",
    "tests/*",
]

[workspace.dependencies]
heck = "0.5"
latch-n = { path = "./crates/latch-n" }
wit-bindgen = { version = "0.62.0", features = ["async-spawn"], git = "https://github.com/bytecodealliance/wit-bindgen.git", branch = "main" }
