[workspace]
resolver = "2"
members = [
    "components/*",
    "crates/*",
]
exclude = [
    "components/gate"
]

[workspace.dependencies]
heck = "0.5"
latch-n = { path = "./crates/latch-n" }
wit-bindgen = { version = "0.58.0", features = ["async-spawn"], git = "https://github.com/scothis/wit-bindgen.git", branch = "macro-merge-structurally-equal-types" }
