[workspace]
resolver = "2"
members = [
    "components/*/src/..",
    "crates/*",
]

[workspace.dependencies]
gate-tests = { path = "./crates/gate-tests" }
heck = "0.5"
latch-n = { path = "./crates/latch-n" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "io-util", "sync", "time"] }
wac-graph = "0.11"
wasmtime = { version = "49", features = ["component-model-async"] }
wasmtime-wasi = { version = "49", features = ["p3"] }
wit-bindgen = { version = "0.62.0", features = ["async-spawn"], git = "https://github.com/bytecodealliance/wit-bindgen.git", branch = "main" }
