[package]
name = "gate-types"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.componentized]
# listen spawns a cooperative thread, which requires wasi-libc's coop threads support on wasm32-wasip3
rust-target = "wasm32-wasip3"

[dependencies]
wit-bindgen = { workspace = true }

[dev-dependencies]
gate-tests = { workspace = true }
tokio = { workspace = true }
wasmtime = { workspace = true }
