[package]
name = "trace-types"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
componentized-rt = { workspace = true, features = ["executor"] }
wit-bindgen = { workspace = true }

[dev-dependencies]
test-harness = { workspace = true }
tokio = { workspace = true }
wasmtime = { workspace = true }
