[package]
name = "latch-cidr-ingress"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
latch-cidr = { workspace = true, features = ["latch"] }
sockets-latch = { workspace = true }

[dev-dependencies]
test-harness = { workspace = true }
tokio = { workspace = true }
wasmtime = { workspace = true }
